=== gmarciani/robomap/robomap/src/robomap/xml/planimetry.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT PLANIMETRY (HOME+)>
<!ELEMENT HOME (ROOM+, WALL*, DOOR*)>
<!ELEMENT ROOM (OBJECT*)>
<!ELEMENT WALL EMPTY>
<!ELEMENT DOOR EMPTY>
<!ELEMENT OBJECT EMPTY>

<!ATTLIST HOME name CDATA #REQUIRED>
<!ATTLIST HOME width CDATA #REQUIRED>
<!ATTLIST HOME height CDATA #REQUIRED>
<!ATTLIST HOME startx CDATA #REQUIRED>
<!ATTLIST HOME starty CDATA #REQUIRED>

<!ATTLIST ROOM name CDATA #REQUIRED>
<!ATTLIST ROOM x CDATA #REQUIRED>
<!ATTLIST ROOM y CDATA #REQUIRED>
<!ATTLIST ROOM width CDATA #REQUIRED>
<!ATTLIST ROOM height CDATA #REQUIRED>

<!ATTLIST WALL x CDATA #REQUIRED>
<!ATTLIST WALL y CDATA #REQUIRED>
<!ATTLIST WALL orientation (RIGHT|FORWARD) #REQUIRED>
<!ATTLIST WALL lenght CDATA #REQUIRED>

<!ATTLIST DOOR x CDATA #REQUIRED>
<!ATTLIST DOOR y CDATA #REQUIRED>
<!ATTLIST DOOR orientation (RIGHT|FORWARD) #REQUIRED>
<!ATTLIST DOOR lenght CDATA #REQUIRED>

<!ATTLIST OBJECT name CDATA #REQUIRED>
<!ATTLIST OBJECT x CDATA #REQUIRED>
<!ATTLIST OBJECT y CDATA #REQUIRED>
<!ATTLIST OBJECT width CDATA "0">
<!ATTLIST OBJECT height CDATA "0">
<!ATTLIST OBJECT orientation (RIGHT|FORWARD|LEFT|BACKWARD) "RIGHT">
<!ATTLIST OBJECT status CDATA "NONE">

=== gmarciani/robomap/robomap/src/robomap/test/sample_home.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PLANIMETRY SYSTEM "../xml/planimetry.dtd" >
<PLANIMETRY>
  <HOME name="sweet_home" width="100" height="100">
    <ROOM name="corridor" width="50" height="10" x="0" y="60"/>
    <ROOM name="studio" width="25" height="60" x="0" y="0"/>
    <ROOM name="bedroom1" width="40" height="30" x="0" y="70"/>
    <ROOM name="bedroom2" width="25" height="60" x="25" y="20"/>
    <ROOM name="bedroom3" width="25" height="60" x="50" y="0"/>
    <ROOM name="bathroom" width="10" height="30" x="40" y="70"/>
    <ROOM name="kitchen" width="25" height="60" x="75" y="0"/>
    <ROOM name="lounge" width="50" height="40" x="50" y="60"/>
    
    <WALL width="0" height="60" x="25" y="0"/>
    <WALL width="0" height="60" x="50" y="0"/>
    <WALL width="0" height="60" x="75" y="0"/>
    <WALL width="0" height="30" x="40" y="70"/>
    <WALL width="0" height="30" x="50" y="70"/>
    
    <WALL width="10" height="0" x="0" y="60"/>
    <WALL width="20" height="0" x="15" y="60"/>
    <WALL width="20" height="0" x="40" y="60"/>
    <WALL width="20" height="0" x="65" y="60"/>
    <WALL width="10" height="0" x="90" y="60"/>
    <WALL width="10" height="0" x="0" y="70"/>
    <WALL width="25" height="0" x="15" y="70"/>
    <WALL width="5" height="0" x="45" y="70"/>    
    
    <DOOR width="5" height="0" x="10" y="60"/>  
    <DOOR width="5" height="0" x="35" y="60"/>  
    <DOOR width="5" height="0" x="60" y="60"/> 
    <DOOR width="5" height="0" x="85" y="60"/> 
    <DOOR width="5" height="0" x="10" y="70"/> 
    <DOOR width="5" height="0" x="40" y="70"/> 
    
  </HOME>
</PLANIMETRY>

=== gmarciani/robomap/robomap/test/sample_home.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PLANIMETRY SYSTEM "../src/robomap/xml/planimetry.dtd" >

<PLANIMETRY>
    
  	<HOME name="sweet_home" width="10" height="10" startx="0" starty="0">
      
    	<ROOM name="room1" x="0" y="0" width="5" height="5">
    		<OBJECT name="table1" x="1" y="2" width="2" height="2" orientation="RIGHT" />
    	</ROOM>
    	
    	<ROOM name="room2" x="5" y="0" width="5" height="5">
        	<OBJECT name="table2" x="6" y="2" width="2" height="2" orientation="RIGHT" />
    	</ROOM>
    	
    	<ROOM name="room3" x="0" y="5" width="5" height="5">
        	<OBJECT name="table3" x="2" y="7" width="1" height="1" orientation="RIGHT" />
    	</ROOM>
    	
    	<ROOM name="room4" x="5" y="5" width="2" height="5"/>
    	
    	<ROOM name="room5" x="7" y="5" width="3" height="5">
        	<OBJECT name="table5" x="7" y="7" width="1" height="2" orientation="RIGHT" />
    	</ROOM>
    
    	<WALL x="0" y="5" orientation="RIGHT" lenght="2"/>
    	<WALL x="3" y="5" orientation="RIGHT" lenght="3"/>
    	<WALL x="7" y="5" orientation="RIGHT" lenght="1"/>
    	<WALL x="9" y="5" orientation="RIGHT" lenght="1"/>
    	<WALL x="5" y="0" orientation="FORWARD" lenght="1"/>
    	<WALL x="5" y="2" orientation="FORWARD" lenght="4"/>
    	<WALL x="5" y="7" orientation="FORWARD" lenght="3"/> 
    	<WALL x="7" y="5" orientation="FORWARD" lenght="1"/>   
    	<WALL x="7" y="7" orientation="FORWARD" lenght="3"/>   
    
    	<DOOR x="2" y="5" orientation="RIGHT" lenght="1" />  
    	<DOOR x="6" y="5" orientation="RIGHT" lenght="1" />  
    	<DOOR x="8" y="5" orientation="RIGHT" lenght="1"/>  
    	<DOOR x="5" y="1" orientation="FORWARD" lenght="1"/>  
    	<DOOR x="5" y="6" orientation="FORWARD" lenght="1"/>
    	<DOOR x="7" y="6" orientation="FORWARD" lenght="1"/>
    
  	</HOME>
  
</PLANIMETRY>

=== gmarciani/robomap/data/sample_home.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PLANIMETRY SYSTEM "../src/robomap/xml/planimetry.dtd" >

<PLANIMETRY>
    
  	<HOME name="basili_home" width="19" height="11" startx="1" starty="0">
      
    	<ROOM name="ingresso" x="0" y="0" width="4" height="7">
    		<OBJECT name="cappelliera" x="0" y="0" width="1" height="1" orientation="RIGHT"/>
    		<OBJECT name="attaccapanni" x="3" y="3" width="1" height="2" orientation="LEFT"/>
    	</ROOM>
    	
    	<ROOM name="camera_da_letto_1" x="0" y="7" width="5" height="4">
    	    <OBJECT name="letto_matrimoniale" x="0" y="8" width="2" height="2" orientation="RIGHT"/>
        	<OBJECT name="comodino" x="0" y="7" width="1" height="1" orientation="RIGHT"/>        	
        	<OBJECT name="comodino" x="0" y="10" width="1" height="1" orientation="RIGHT"/>
        	<OBJECT name="armadio" x="4" y="7" width="1" height="4" orientation="LEFT"/>
    	</ROOM>
    	
    	<ROOM name="corridoio_1" x="5" y="5" width="6" height="3"/>
    	
    	<ROOM name="bagno" x="5" y="8" width="6" height="3">        	
        	<OBJECT name="bidet" x="5" y="10" width="1" height="1" orientation="BACKWARD"/>
        	<OBJECT name="water" x="7" y="10" width="1" height="1" orientation="BACKWARD"/>
        	<OBJECT name="lavandino" x="6" y="8" width="1" height="1" orientation="FORWARD"/>
        	<OBJECT name="doccia" x="9" y="9" width="2" height="2" orientation="LEFT"/>
    	</ROOM>
    	
    	<ROOM name="salotto" x="11" y="5" width="8" height="6">
        	<OBJECT name="televisione" x="11" y="8" width="1" height="2" orientation="RIGHT" status="OFF">
        	    <INTERACTION name="SWITCH_ON"/>
        	    <INTERACTION name="SWITCH_OFF"/>
        	</OBJECT>
        	<OBJECT name="divano" x="14" y="8" width="1" height="2" orientation="LEFT">
        	    <INTERACTION name="CLEAN"/>
        	</OBJECT>
        	<OBJECT name="tavolo" x="17" y="9" width="1" height="1" orientation="LEFT"/>
    	</ROOM>
    	
    	<ROOM name="cucina" x="13" y="0" width="6" height="5">
    	    <OBJECT name="frigo" x="18" y="3" width="1" height="2" orientation="LEFT" status="ON">
    	        <INTERACTION name="SWITCH_ON"/>
        	    <INTERACTION name="SWITCH_OFF"/>
    	    </OBJECT>
        	<OBJECT name="lavello" x="13" y="0" width="6" height="1" orientation="FORWARD"/>
        	<OBJECT name="cestino" x="13" y="4" width="1" height="1" orientation="RIGHT"/>        	
    	</ROOM>
    	
    	<ROOM name="corridoio_2" x="4" y="0" width="9" height="2"/>
    	
    	<ROOM name="ripostiglio" x="9" y="2" width="4" height="3"/>
    	
    	<ROOM name="camera_da_letto_2" x="4" y="2" width="5" height="3">
        	<OBJECT name="letto" x="4" y="3" width="2" height="1" orientation="RIGHT"/>
        	<OBJECT name="comodino" x="4" y="4" width="1" height="1" orientation="RIGHT"/>
        	<OBJECT name="cassettiera" x="8" y="4" width="1" height="1" orientation="BACKWARD"/>
    	</ROOM>    	
    
    	<WALL x="0" y="7" orientation="RIGHT" lenght="3"/>
    	<WALL x="4" y="2" orientation="RIGHT" lenght="3"/>
    	<WALL x="4" y="5" orientation="RIGHT" lenght="9"/>
    	<WALL x="4" y="7" orientation="RIGHT" lenght="1"/>
    	<WALL x="5" y="8" orientation="RIGHT" lenght="3"/>
    	<WALL x="8" y="2" orientation="RIGHT" lenght="3"/>
    	<WALL x="9" y="8" orientation="RIGHT" lenght="2"/>
    	<WALL x="12" y="2" orientation="RIGHT" lenght="1"/>    	
    	
    	<WALL x="4" y="1" orientation="FORWARD" lenght="4"/>
    	<WALL x="5" y="7" orientation="FORWARD" lenght="4"/> 
    	<WALL x="9" y="2" orientation="FORWARD" lenght="3"/>   
    	<WALL x="11" y="8" orientation="FORWARD" lenght="3"/>   
    	<WALL x="13" y="0" orientation="FORWARD" lenght="5"/>
    
    	<DOOR x="3" y="7" orientation="RIGHT" lenght="1" />  
    	<DOOR x="7" y="2" orientation="RIGHT" lenght="1" />  
    	<DOOR x="8" y="8" orientation="RIGHT" lenght="1"/>  
    	<DOOR x="11" y="2" orientation="RIGHT" lenght="1"/>  
    	
    	<DOOR x="4" y="0" orientation="FORWARD" lenght="1"/>  
    
  	</HOME>
  
</PLANIMETRY>
